/*
 * generated by Xtext
 */
package org.xtext.StateMachine.sm;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class SMRuntimeModule extends org.xtext.StateMachine.sm.AbstractSMRuntimeModule {

}
