/*
 * generated by Xtext
 */
package org.xtext.StateMachine.sm.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.xtext.StateMachine.sm.services.SMGrammarAccess;

public class SMParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private SMGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.xtext.StateMachine.sm.parser.antlr.internal.InternalSMParser createParser(XtextTokenStream stream) {
		return new org.xtext.StateMachine.sm.parser.antlr.internal.InternalSMParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "StateMachine";
	}
	
	public SMGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(SMGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
