/**
 * generated by Xtext
 */
package org.xtext.StateMachine.sm.ui.contentassist;

import org.xtext.StateMachine.sm.ui.contentassist.AbstractSMProposalProvider;

/**
 * See https://www.eclipse.org/Xtext/documentation/304_ide_concepts.html#content-assist
 * on how to customize the content assistant.
 */
@SuppressWarnings("all")
public class SMProposalProvider extends AbstractSMProposalProvider {
}
