/*
 * generated by Xtext
 */
package org.xtext.StateMachine.sm;

/**
 * Initialization support for running Xtext languages 
 * without equinox extension registry
 */
public class SMStandaloneSetup extends SMStandaloneSetupGenerated{

	public static void doSetup() {
		new SMStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}

