/*
 * generated by Xtext
 */
package org.xtext.StateMachine.sm.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class SMUiModule extends org.xtext.StateMachine.sm.ui.AbstractSMUiModule {
	public SMUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
