/*
 * generated by Xtext
 */
package org.xtext.StateMachine.sm;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class SMUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.StateMachine.sm.ui.internal.SMActivator.getInstance().getInjector("org.xtext.StateMachine.sm.SM");
	}
	
}
