/*
 * generated by Xtext
 */
package org.xtext.StateMachine.sm.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import java.util.List;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class SMGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class StateMachineElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "StateMachine");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsActiveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsActiveIsActiveKeyword_0_0 = (Keyword)cIsActiveAssignment_0.eContents().get(0);
		private final Keyword cStateMachineKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVariablesAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final RuleCall cVariablesVariableParserRuleCall_4_0 = (RuleCall)cVariablesAssignment_4.eContents().get(0);
		private final Keyword cEventsKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEventsAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cEventsEventParserRuleCall_7_0 = (RuleCall)cEventsAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cEventsAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cEventsEventParserRuleCall_8_1_0 = (RuleCall)cEventsAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cRightCurlyBracketKeyword_10 = (Keyword)cGroup.eContents().get(10);
		
		//StateMachine:
		//	isActive?="isActive" "StateMachine" name=EString "{" variables+=Variable* "events" "{" events+=Event (","
		//	events+=Event)* "}" / *('operation' operation=Operation)?
		//		'states' '{' states+=State ( "," states+=State)* '}' 
		//		'initialState' initialState=InitialState
		//		'transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' 
		//		'events' '{' events+=Event ( "," events+=Event)* '}' 
		//		('variables' '{' variables+=Variable ( "," variables+=Variable)* '}' )?* / "}";
		@Override public ParserRule getRule() { return rule; }

		//isActive?="isActive" "StateMachine" name=EString "{" variables+=Variable* "events" "{" events+=Event (","
		//events+=Event)* "}" / *('operation' operation=Operation)?
		//		'states' '{' states+=State ( "," states+=State)* '}' 
		//		'initialState' initialState=InitialState
		//		'transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' 
		//		'events' '{' events+=Event ( "," events+=Event)* '}' 
		//		('variables' '{' variables+=Variable ( "," variables+=Variable)* '}' )?* / "}"
		public Group getGroup() { return cGroup; }

		//isActive?="isActive"
		public Assignment getIsActiveAssignment_0() { return cIsActiveAssignment_0; }

		//"isActive"
		public Keyword getIsActiveIsActiveKeyword_0_0() { return cIsActiveIsActiveKeyword_0_0; }

		//"StateMachine"
		public Keyword getStateMachineKeyword_1() { return cStateMachineKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//variables+=Variable*
		public Assignment getVariablesAssignment_4() { return cVariablesAssignment_4; }

		//Variable
		public RuleCall getVariablesVariableParserRuleCall_4_0() { return cVariablesVariableParserRuleCall_4_0; }

		//"events"
		public Keyword getEventsKeyword_5() { return cEventsKeyword_5; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }

		//events+=Event
		public Assignment getEventsAssignment_7() { return cEventsAssignment_7; }

		//Event
		public RuleCall getEventsEventParserRuleCall_7_0() { return cEventsEventParserRuleCall_7_0; }

		//("," events+=Event)*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//events+=Event
		public Assignment getEventsAssignment_8_1() { return cEventsAssignment_8_1; }

		//Event
		public RuleCall getEventsEventParserRuleCall_8_1_0() { return cEventsEventParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }

		/// *('operation' operation=Operation)?
		//		'states' '{' states+=State ( "," states+=State)* '}' 
		//		'initialState' initialState=InitialState
		//		'transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' 
		//		'events' '{' events+=Event ( "," events+=Event)* '}' 
		//		('variables' '{' variables+=Variable ( "," variables+=Variable)* '}' )?* / "}"
		public Keyword getRightCurlyBracketKeyword_10() { return cRightCurlyBracketKeyword_10; }
	}

	public class StateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cState_ImplParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cStateMachineParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cCompositeState_ImplParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		
		//State:
		//	State_Impl | StateMachine | CompositeState_Impl;
		@Override public ParserRule getRule() { return rule; }

		//State_Impl | StateMachine | CompositeState_Impl
		public Alternatives getAlternatives() { return cAlternatives; }

		//State_Impl
		public RuleCall getState_ImplParserRuleCall_0() { return cState_ImplParserRuleCall_0; }

		//StateMachine
		public RuleCall getStateMachineParserRuleCall_1() { return cStateMachineParserRuleCall_1; }

		//CompositeState_Impl
		public RuleCall getCompositeState_ImplParserRuleCall_2() { return cCompositeState_ImplParserRuleCall_2; }
	}

	public class VariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Variable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVarKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final RuleCall cBooleanVariableParserRuleCall_1_0 = (RuleCall)cAlternatives_1.eContents().get(0);
		private final RuleCall cIntegerVariableParserRuleCall_1_1 = (RuleCall)cAlternatives_1.eContents().get(1);
		
		//Variable:
		//	"var" (BooleanVariable | IntegerVariable);
		@Override public ParserRule getRule() { return rule; }

		//"var" (BooleanVariable | IntegerVariable)
		public Group getGroup() { return cGroup; }

		//"var"
		public Keyword getVarKeyword_0() { return cVarKeyword_0; }

		//BooleanVariable | IntegerVariable
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//BooleanVariable
		public RuleCall getBooleanVariableParserRuleCall_1_0() { return cBooleanVariableParserRuleCall_1_0; }

		//IntegerVariable
		public RuleCall getIntegerVariableParserRuleCall_1_1() { return cIntegerVariableParserRuleCall_1_1; }
	}

	public class ExpressionElementElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpressionElement");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cExpressionParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cBooleanDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIntegerDataParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cVariableReferenceParserRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//ExpressionElement:
		//	Expression | BooleanData | IntegerData | VariableReference;
		@Override public ParserRule getRule() { return rule; }

		//Expression | BooleanData | IntegerData | VariableReference
		public Alternatives getAlternatives() { return cAlternatives; }

		//Expression
		public RuleCall getExpressionParserRuleCall_0() { return cExpressionParserRuleCall_0; }

		//BooleanData
		public RuleCall getBooleanDataParserRuleCall_1() { return cBooleanDataParserRuleCall_1; }

		//IntegerData
		public RuleCall getIntegerDataParserRuleCall_2() { return cIntegerDataParserRuleCall_2; }

		//VariableReference
		public RuleCall getVariableReferenceParserRuleCall_3() { return cVariableReferenceParserRuleCall_3; }
	}

	public class DataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Data");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBooleanDataParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIntegerDataParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//Data:
		//	BooleanData | IntegerData;
		@Override public ParserRule getRule() { return rule; }

		//BooleanData | IntegerData
		public Alternatives getAlternatives() { return cAlternatives; }

		//BooleanData
		public RuleCall getBooleanDataParserRuleCall_0() { return cBooleanDataParserRuleCall_0; }

		//IntegerData
		public RuleCall getIntegerDataParserRuleCall_1() { return cIntegerDataParserRuleCall_1; }
	}

	public class EStringElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EString");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cSTRINGTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cIDTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//EString returns ecore::EString:
		//	STRING | ID;
		@Override public ParserRule getRule() { return rule; }

		//STRING | ID
		public Alternatives getAlternatives() { return cAlternatives; }

		//STRING
		public RuleCall getSTRINGTerminalRuleCall_0() { return cSTRINGTerminalRuleCall_0; }

		//ID
		public RuleCall getIDTerminalRuleCall_1() { return cIDTerminalRuleCall_1; }
	}

	public class EBooleanElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EBoolean");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Keyword cTrueKeyword_0 = (Keyword)cAlternatives.eContents().get(0);
		private final Keyword cFalseKeyword_1 = (Keyword)cAlternatives.eContents().get(1);
		
		//EBoolean returns ecore::EBoolean:
		//	"true" | "false";
		@Override public ParserRule getRule() { return rule; }

		//"true" | "false"
		public Alternatives getAlternatives() { return cAlternatives; }

		//"true"
		public Keyword getTrueKeyword_0() { return cTrueKeyword_0; }

		//"false"
		public Keyword getFalseKeyword_1() { return cFalseKeyword_1; }
	}

	public class OperationElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Operation");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cOperationAction_0 = (Action)cGroup.eContents().get(0);
		private final Keyword cOperationKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cLeftCurlyBracketKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Group cGroup_3 = (Group)cGroup.eContents().get(3);
		private final Keyword cContentsKeyword_3_0 = (Keyword)cGroup_3.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3_1 = (Keyword)cGroup_3.eContents().get(1);
		private final Assignment cContentsAssignment_3_2 = (Assignment)cGroup_3.eContents().get(2);
		private final RuleCall cContentsAssignmentParserRuleCall_3_2_0 = (RuleCall)cContentsAssignment_3_2.eContents().get(0);
		private final Group cGroup_3_3 = (Group)cGroup_3.eContents().get(3);
		private final Keyword cCommaKeyword_3_3_0 = (Keyword)cGroup_3_3.eContents().get(0);
		private final Assignment cContentsAssignment_3_3_1 = (Assignment)cGroup_3_3.eContents().get(1);
		private final RuleCall cContentsAssignmentParserRuleCall_3_3_1_0 = (RuleCall)cContentsAssignment_3_3_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_3_4 = (Keyword)cGroup_3.eContents().get(4);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//Operation:
		//	{Operation} "Operation" "{" ("contents" "{" contents+=Assignment ("," contents+=Assignment)* "}")? "}";
		@Override public ParserRule getRule() { return rule; }

		//{Operation} "Operation" "{" ("contents" "{" contents+=Assignment ("," contents+=Assignment)* "}")? "}"
		public Group getGroup() { return cGroup; }

		//{Operation}
		public Action getOperationAction_0() { return cOperationAction_0; }

		//"Operation"
		public Keyword getOperationKeyword_1() { return cOperationKeyword_1; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_2() { return cLeftCurlyBracketKeyword_2; }

		//("contents" "{" contents+=Assignment ("," contents+=Assignment)* "}")?
		public Group getGroup_3() { return cGroup_3; }

		//"contents"
		public Keyword getContentsKeyword_3_0() { return cContentsKeyword_3_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3_1() { return cLeftCurlyBracketKeyword_3_1; }

		//contents+=Assignment
		public Assignment getContentsAssignment_3_2() { return cContentsAssignment_3_2; }

		//Assignment
		public RuleCall getContentsAssignmentParserRuleCall_3_2_0() { return cContentsAssignmentParserRuleCall_3_2_0; }

		//("," contents+=Assignment)*
		public Group getGroup_3_3() { return cGroup_3_3; }

		//","
		public Keyword getCommaKeyword_3_3_0() { return cCommaKeyword_3_3_0; }

		//contents+=Assignment
		public Assignment getContentsAssignment_3_3_1() { return cContentsAssignment_3_3_1; }

		//Assignment
		public RuleCall getContentsAssignmentParserRuleCall_3_3_1_0() { return cContentsAssignmentParserRuleCall_3_3_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_3_4() { return cRightCurlyBracketKeyword_3_4; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class State_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "State_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsActiveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsActiveIsActiveKeyword_0_0 = (Keyword)cIsActiveAssignment_0.eContents().get(0);
		private final Keyword cStateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOperationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOperationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOperationOperationParserRuleCall_4_1_0 = (RuleCall)cOperationAssignment_4_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//State_Impl returns State:
		//	isActive?="isActive" "State" name=EString "{" ("operation" operation=Operation)? "}";
		@Override public ParserRule getRule() { return rule; }

		//isActive?="isActive" "State" name=EString "{" ("operation" operation=Operation)? "}"
		public Group getGroup() { return cGroup; }

		//isActive?="isActive"
		public Assignment getIsActiveAssignment_0() { return cIsActiveAssignment_0; }

		//"isActive"
		public Keyword getIsActiveIsActiveKeyword_0_0() { return cIsActiveIsActiveKeyword_0_0; }

		//"State"
		public Keyword getStateKeyword_1() { return cStateKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("operation" operation=Operation)?
		public Group getGroup_4() { return cGroup_4; }

		//"operation"
		public Keyword getOperationKeyword_4_0() { return cOperationKeyword_4_0; }

		//operation=Operation
		public Assignment getOperationAssignment_4_1() { return cOperationAssignment_4_1; }

		//Operation
		public RuleCall getOperationOperationParserRuleCall_4_1_0() { return cOperationOperationParserRuleCall_4_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class InitialStateElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "InitialState");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cInitialStateKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cReferencedStateKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cReferencedStateAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cReferencedStateStateCrossReference_3_0 = (CrossReference)cReferencedStateAssignment_3.eContents().get(0);
		private final RuleCall cReferencedStateStateEStringParserRuleCall_3_0_1 = (RuleCall)cReferencedStateStateCrossReference_3_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_4 = (Keyword)cGroup.eContents().get(4);
		
		//InitialState:
		//	"InitialState" "{" "referencedState" referencedState=[State|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"InitialState" "{" "referencedState" referencedState=[State|EString] "}"
		public Group getGroup() { return cGroup; }

		//"InitialState"
		public Keyword getInitialStateKeyword_0() { return cInitialStateKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"referencedState"
		public Keyword getReferencedStateKeyword_2() { return cReferencedStateKeyword_2; }

		//referencedState=[State|EString]
		public Assignment getReferencedStateAssignment_3() { return cReferencedStateAssignment_3; }

		//[State|EString]
		public CrossReference getReferencedStateStateCrossReference_3_0() { return cReferencedStateStateCrossReference_3_0; }

		//EString
		public RuleCall getReferencedStateStateEStringParserRuleCall_3_0_1() { return cReferencedStateStateEStringParserRuleCall_3_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_4() { return cRightCurlyBracketKeyword_4; }
	}

	public class TransitionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Transition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cTransitionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cSourceKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cSourceAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cSourceStateCrossReference_3_0 = (CrossReference)cSourceAssignment_3.eContents().get(0);
		private final RuleCall cSourceStateEStringParserRuleCall_3_0_1 = (RuleCall)cSourceStateCrossReference_3_0.eContents().get(1);
		private final Keyword cTargetKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final Assignment cTargetAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final CrossReference cTargetStateCrossReference_5_0 = (CrossReference)cTargetAssignment_5.eContents().get(0);
		private final RuleCall cTargetStateEStringParserRuleCall_5_0_1 = (RuleCall)cTargetStateCrossReference_5_0.eContents().get(1);
		private final Keyword cEventKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cEventAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final CrossReference cEventEventCrossReference_7_0 = (CrossReference)cEventAssignment_7.eContents().get(0);
		private final RuleCall cEventEventEStringParserRuleCall_7_0_1 = (RuleCall)cEventEventCrossReference_7_0.eContents().get(1);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cGuardKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cGuardAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cGuardExpressionParserRuleCall_8_1_0 = (RuleCall)cGuardAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Transition:
		//	"Transition" "{" "source" source=[State|EString] "target" target=[State|EString] "event" event=[Event|EString]
		//	("guard" guard=Expression)? "}";
		@Override public ParserRule getRule() { return rule; }

		//"Transition" "{" "source" source=[State|EString] "target" target=[State|EString] "event" event=[Event|EString] ("guard"
		//guard=Expression)? "}"
		public Group getGroup() { return cGroup; }

		//"Transition"
		public Keyword getTransitionKeyword_0() { return cTransitionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"source"
		public Keyword getSourceKeyword_2() { return cSourceKeyword_2; }

		//source=[State|EString]
		public Assignment getSourceAssignment_3() { return cSourceAssignment_3; }

		//[State|EString]
		public CrossReference getSourceStateCrossReference_3_0() { return cSourceStateCrossReference_3_0; }

		//EString
		public RuleCall getSourceStateEStringParserRuleCall_3_0_1() { return cSourceStateEStringParserRuleCall_3_0_1; }

		//"target"
		public Keyword getTargetKeyword_4() { return cTargetKeyword_4; }

		//target=[State|EString]
		public Assignment getTargetAssignment_5() { return cTargetAssignment_5; }

		//[State|EString]
		public CrossReference getTargetStateCrossReference_5_0() { return cTargetStateCrossReference_5_0; }

		//EString
		public RuleCall getTargetStateEStringParserRuleCall_5_0_1() { return cTargetStateEStringParserRuleCall_5_0_1; }

		//"event"
		public Keyword getEventKeyword_6() { return cEventKeyword_6; }

		//event=[Event|EString]
		public Assignment getEventAssignment_7() { return cEventAssignment_7; }

		//[Event|EString]
		public CrossReference getEventEventCrossReference_7_0() { return cEventEventCrossReference_7_0; }

		//EString
		public RuleCall getEventEventEStringParserRuleCall_7_0_1() { return cEventEventEStringParserRuleCall_7_0_1; }

		//("guard" guard=Expression)?
		public Group getGroup_8() { return cGroup_8; }

		//"guard"
		public Keyword getGuardKeyword_8_0() { return cGuardKeyword_8_0; }

		//guard=Expression
		public Assignment getGuardAssignment_8_1() { return cGuardAssignment_8_1; }

		//Expression
		public RuleCall getGuardExpressionParserRuleCall_8_1_0() { return cGuardExpressionParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class EventElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Event");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cEventAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameSTRINGTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		
		//Event:
		//	{Event} name=STRING;
		@Override public ParserRule getRule() { return rule; }

		//{Event} name=STRING
		public Group getGroup() { return cGroup; }

		//{Event}
		public Action getEventAction_0() { return cEventAction_0; }

		//name=STRING
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//STRING
		public RuleCall getNameSTRINGTerminalRuleCall_1_0() { return cNameSTRINGTerminalRuleCall_1_0; }
	}

	public class AssignmentElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Assignment");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cAssignmentKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword c_nameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment c_nameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall c_nameEStringParserRuleCall_2_1_0 = (RuleCall)c_nameAssignment_2_1.eContents().get(0);
		private final Keyword cVariableKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVariableAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cVariableVariableCrossReference_4_0 = (CrossReference)cVariableAssignment_4.eContents().get(0);
		private final RuleCall cVariableVariableEStringParserRuleCall_4_0_1 = (RuleCall)cVariableVariableCrossReference_4_0.eContents().get(1);
		private final Keyword cExpressionKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cExpressionAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cExpressionExpressionElementParserRuleCall_6_0 = (RuleCall)cExpressionAssignment_6.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_7 = (Keyword)cGroup.eContents().get(7);
		
		//Assignment:
		//	"Assignment" "{" ("_name" _name=EString)? "variable" variable=[Variable|EString] "expression"
		//	expression=ExpressionElement "}";
		@Override public ParserRule getRule() { return rule; }

		//"Assignment" "{" ("_name" _name=EString)? "variable" variable=[Variable|EString] "expression"
		//expression=ExpressionElement "}"
		public Group getGroup() { return cGroup; }

		//"Assignment"
		public Keyword getAssignmentKeyword_0() { return cAssignmentKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("_name" _name=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"_name"
		public Keyword get_nameKeyword_2_0() { return c_nameKeyword_2_0; }

		//_name=EString
		public Assignment get_nameAssignment_2_1() { return c_nameAssignment_2_1; }

		//EString
		public RuleCall get_nameEStringParserRuleCall_2_1_0() { return c_nameEStringParserRuleCall_2_1_0; }

		//"variable"
		public Keyword getVariableKeyword_3() { return cVariableKeyword_3; }

		//variable=[Variable|EString]
		public Assignment getVariableAssignment_4() { return cVariableAssignment_4; }

		//[Variable|EString]
		public CrossReference getVariableVariableCrossReference_4_0() { return cVariableVariableCrossReference_4_0; }

		//EString
		public RuleCall getVariableVariableEStringParserRuleCall_4_0_1() { return cVariableVariableEStringParserRuleCall_4_0_1; }

		//"expression"
		public Keyword getExpressionKeyword_5() { return cExpressionKeyword_5; }

		//expression=ExpressionElement
		public Assignment getExpressionAssignment_6() { return cExpressionAssignment_6; }

		//ExpressionElement
		public RuleCall getExpressionExpressionElementParserRuleCall_6_0() { return cExpressionExpressionElementParserRuleCall_6_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_7() { return cRightCurlyBracketKeyword_7; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cExpressionKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Keyword cOperatorKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cOperatorAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cOperatorOperatorEnumRuleCall_3_0 = (RuleCall)cOperatorAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword c_nameKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment c_nameAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall c_nameEStringParserRuleCall_4_1_0 = (RuleCall)c_nameAssignment_4_1.eContents().get(0);
		private final Keyword cLeftKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Assignment cLeftAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cLeftExpressionElementParserRuleCall_6_0 = (RuleCall)cLeftAssignment_6.eContents().get(0);
		private final Keyword cRightKeyword_7 = (Keyword)cGroup.eContents().get(7);
		private final Assignment cRightAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cRightExpressionElementParserRuleCall_8_0 = (RuleCall)cRightAssignment_8.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		
		//Expression:
		//	"Expression" "{" "operator" operator=Operator ("_name" _name=EString)? "left" left=ExpressionElement "right"
		//	right=ExpressionElement "}";
		@Override public ParserRule getRule() { return rule; }

		//"Expression" "{" "operator" operator=Operator ("_name" _name=EString)? "left" left=ExpressionElement "right"
		//right=ExpressionElement "}"
		public Group getGroup() { return cGroup; }

		//"Expression"
		public Keyword getExpressionKeyword_0() { return cExpressionKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//"operator"
		public Keyword getOperatorKeyword_2() { return cOperatorKeyword_2; }

		//operator=Operator
		public Assignment getOperatorAssignment_3() { return cOperatorAssignment_3; }

		//Operator
		public RuleCall getOperatorOperatorEnumRuleCall_3_0() { return cOperatorOperatorEnumRuleCall_3_0; }

		//("_name" _name=EString)?
		public Group getGroup_4() { return cGroup_4; }

		//"_name"
		public Keyword get_nameKeyword_4_0() { return c_nameKeyword_4_0; }

		//_name=EString
		public Assignment get_nameAssignment_4_1() { return c_nameAssignment_4_1; }

		//EString
		public RuleCall get_nameEStringParserRuleCall_4_1_0() { return c_nameEStringParserRuleCall_4_1_0; }

		//"left"
		public Keyword getLeftKeyword_5() { return cLeftKeyword_5; }

		//left=ExpressionElement
		public Assignment getLeftAssignment_6() { return cLeftAssignment_6; }

		//ExpressionElement
		public RuleCall getLeftExpressionElementParserRuleCall_6_0() { return cLeftExpressionElementParserRuleCall_6_0; }

		//"right"
		public Keyword getRightKeyword_7() { return cRightKeyword_7; }

		//right=ExpressionElement
		public Assignment getRightAssignment_8() { return cRightAssignment_8; }

		//ExpressionElement
		public RuleCall getRightExpressionElementParserRuleCall_8_0() { return cRightExpressionElementParserRuleCall_8_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }
	}

	public class BooleanDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanData");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEBooleanParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//BooleanData:
		//	value=EBoolean;
		@Override public ParserRule getRule() { return rule; }

		//value=EBoolean
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EBoolean
		public RuleCall getValueEBooleanParserRuleCall_0() { return cValueEBooleanParserRuleCall_0; }
	}

	public class IntegerDataElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntegerData");
		private final Assignment cValueAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cValueEIntParserRuleCall_0 = (RuleCall)cValueAssignment.eContents().get(0);
		
		//IntegerData:
		//	value=EInt;
		@Override public ParserRule getRule() { return rule; }

		//value=EInt
		public Assignment getValueAssignment() { return cValueAssignment; }

		//EInt
		public RuleCall getValueEIntParserRuleCall_0() { return cValueEIntParserRuleCall_0; }
	}

	public class VariableReferenceElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "VariableReference");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cVariableReferenceKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Group cGroup_2 = (Group)cGroup.eContents().get(2);
		private final Keyword c_nameKeyword_2_0 = (Keyword)cGroup_2.eContents().get(0);
		private final Assignment c_nameAssignment_2_1 = (Assignment)cGroup_2.eContents().get(1);
		private final RuleCall c_nameEStringParserRuleCall_2_1_0 = (RuleCall)c_nameAssignment_2_1.eContents().get(0);
		private final Keyword cVariableKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Assignment cVariableAssignment_4 = (Assignment)cGroup.eContents().get(4);
		private final CrossReference cVariableVariableCrossReference_4_0 = (CrossReference)cVariableAssignment_4.eContents().get(0);
		private final RuleCall cVariableVariableEStringParserRuleCall_4_0_1 = (RuleCall)cVariableVariableCrossReference_4_0.eContents().get(1);
		private final Keyword cRightCurlyBracketKeyword_5 = (Keyword)cGroup.eContents().get(5);
		
		//VariableReference:
		//	"VariableReference" "{" ("_name" _name=EString)? "variable" variable=[Variable|EString] "}";
		@Override public ParserRule getRule() { return rule; }

		//"VariableReference" "{" ("_name" _name=EString)? "variable" variable=[Variable|EString] "}"
		public Group getGroup() { return cGroup; }

		//"VariableReference"
		public Keyword getVariableReferenceKeyword_0() { return cVariableReferenceKeyword_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_1() { return cLeftCurlyBracketKeyword_1; }

		//("_name" _name=EString)?
		public Group getGroup_2() { return cGroup_2; }

		//"_name"
		public Keyword get_nameKeyword_2_0() { return c_nameKeyword_2_0; }

		//_name=EString
		public Assignment get_nameAssignment_2_1() { return c_nameAssignment_2_1; }

		//EString
		public RuleCall get_nameEStringParserRuleCall_2_1_0() { return c_nameEStringParserRuleCall_2_1_0; }

		//"variable"
		public Keyword getVariableKeyword_3() { return cVariableKeyword_3; }

		//variable=[Variable|EString]
		public Assignment getVariableAssignment_4() { return cVariableAssignment_4; }

		//[Variable|EString]
		public CrossReference getVariableVariableCrossReference_4_0() { return cVariableVariableCrossReference_4_0; }

		//EString
		public RuleCall getVariableVariableEStringParserRuleCall_4_0_1() { return cVariableVariableEStringParserRuleCall_4_0_1; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_5() { return cRightCurlyBracketKeyword_5; }
	}

	public class EIntElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "EInt");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cHyphenMinusKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cINTTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		
		//EInt returns ecore::EInt:
		//	"-"? INT;
		@Override public ParserRule getRule() { return rule; }

		//"-"? INT
		public Group getGroup() { return cGroup; }

		//"-"?
		public Keyword getHyphenMinusKeyword_0() { return cHyphenMinusKeyword_0; }

		//INT
		public RuleCall getINTTerminalRuleCall_1() { return cINTTerminalRuleCall_1; }
	}

	public class CompositeState_ImplElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CompositeState_Impl");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cIsActiveAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final Keyword cIsActiveIsActiveKeyword_0_0 = (Keyword)cIsActiveAssignment_0.eContents().get(0);
		private final Keyword cCompositeStateKeyword_1 = (Keyword)cGroup.eContents().get(1);
		private final Assignment cNameAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cNameEStringParserRuleCall_2_0 = (RuleCall)cNameAssignment_2.eContents().get(0);
		private final Keyword cLeftCurlyBracketKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cOperationKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cOperationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cOperationOperationParserRuleCall_4_1_0 = (RuleCall)cOperationAssignment_4_1.eContents().get(0);
		private final Keyword cStatesKeyword_5 = (Keyword)cGroup.eContents().get(5);
		private final Keyword cLeftCurlyBracketKeyword_6 = (Keyword)cGroup.eContents().get(6);
		private final Assignment cStatesAssignment_7 = (Assignment)cGroup.eContents().get(7);
		private final RuleCall cStatesStateParserRuleCall_7_0 = (RuleCall)cStatesAssignment_7.eContents().get(0);
		private final Group cGroup_8 = (Group)cGroup.eContents().get(8);
		private final Keyword cCommaKeyword_8_0 = (Keyword)cGroup_8.eContents().get(0);
		private final Assignment cStatesAssignment_8_1 = (Assignment)cGroup_8.eContents().get(1);
		private final RuleCall cStatesStateParserRuleCall_8_1_0 = (RuleCall)cStatesAssignment_8_1.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_9 = (Keyword)cGroup.eContents().get(9);
		private final Keyword cInitialStateKeyword_10 = (Keyword)cGroup.eContents().get(10);
		private final Assignment cInitialStateAssignment_11 = (Assignment)cGroup.eContents().get(11);
		private final RuleCall cInitialStateInitialStateParserRuleCall_11_0 = (RuleCall)cInitialStateAssignment_11.eContents().get(0);
		private final Keyword cRightCurlyBracketKeyword_12 = (Keyword)cGroup.eContents().get(12);
		
		//CompositeState_Impl returns CompositeState:
		//	isActive?="isActive" "CompositeState" name=EString "{" ("operation" operation=Operation)? "states" "{" states+=State
		//	("," states+=State)* "}" "initialState" initialState=InitialState "}";
		@Override public ParserRule getRule() { return rule; }

		//isActive?="isActive" "CompositeState" name=EString "{" ("operation" operation=Operation)? "states" "{" states+=State
		//("," states+=State)* "}" "initialState" initialState=InitialState "}"
		public Group getGroup() { return cGroup; }

		//isActive?="isActive"
		public Assignment getIsActiveAssignment_0() { return cIsActiveAssignment_0; }

		//"isActive"
		public Keyword getIsActiveIsActiveKeyword_0_0() { return cIsActiveIsActiveKeyword_0_0; }

		//"CompositeState"
		public Keyword getCompositeStateKeyword_1() { return cCompositeStateKeyword_1; }

		//name=EString
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//EString
		public RuleCall getNameEStringParserRuleCall_2_0() { return cNameEStringParserRuleCall_2_0; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_3() { return cLeftCurlyBracketKeyword_3; }

		//("operation" operation=Operation)?
		public Group getGroup_4() { return cGroup_4; }

		//"operation"
		public Keyword getOperationKeyword_4_0() { return cOperationKeyword_4_0; }

		//operation=Operation
		public Assignment getOperationAssignment_4_1() { return cOperationAssignment_4_1; }

		//Operation
		public RuleCall getOperationOperationParserRuleCall_4_1_0() { return cOperationOperationParserRuleCall_4_1_0; }

		//"states"
		public Keyword getStatesKeyword_5() { return cStatesKeyword_5; }

		//"{"
		public Keyword getLeftCurlyBracketKeyword_6() { return cLeftCurlyBracketKeyword_6; }

		//states+=State
		public Assignment getStatesAssignment_7() { return cStatesAssignment_7; }

		//State
		public RuleCall getStatesStateParserRuleCall_7_0() { return cStatesStateParserRuleCall_7_0; }

		//("," states+=State)*
		public Group getGroup_8() { return cGroup_8; }

		//","
		public Keyword getCommaKeyword_8_0() { return cCommaKeyword_8_0; }

		//states+=State
		public Assignment getStatesAssignment_8_1() { return cStatesAssignment_8_1; }

		//State
		public RuleCall getStatesStateParserRuleCall_8_1_0() { return cStatesStateParserRuleCall_8_1_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_9() { return cRightCurlyBracketKeyword_9; }

		//"initialState"
		public Keyword getInitialStateKeyword_10() { return cInitialStateKeyword_10; }

		//initialState=InitialState
		public Assignment getInitialStateAssignment_11() { return cInitialStateAssignment_11; }

		//InitialState
		public RuleCall getInitialStateInitialStateParserRuleCall_11_0() { return cInitialStateInitialStateParserRuleCall_11_0; }

		//"}"
		public Keyword getRightCurlyBracketKeyword_12() { return cRightCurlyBracketKeyword_12; }
	}

	public class BooleanVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BooleanVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cBooleanVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cBooleanKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cColonEqualsSignKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueBooleanDataParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		
		//BooleanVariable:
		//	{BooleanVariable} name=EString ":" "boolean" (":=" value=BooleanData)?;
		@Override public ParserRule getRule() { return rule; }

		//{BooleanVariable} name=EString ":" "boolean" (":=" value=BooleanData)?
		public Group getGroup() { return cGroup; }

		//{BooleanVariable}
		public Action getBooleanVariableAction_0() { return cBooleanVariableAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//"boolean"
		public Keyword getBooleanKeyword_3() { return cBooleanKeyword_3; }

		//(":=" value=BooleanData)?
		public Group getGroup_4() { return cGroup_4; }

		//":="
		public Keyword getColonEqualsSignKeyword_4_0() { return cColonEqualsSignKeyword_4_0; }

		//value=BooleanData
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }

		//BooleanData
		public RuleCall getValueBooleanDataParserRuleCall_4_1_0() { return cValueBooleanDataParserRuleCall_4_1_0; }
	}

	public class IntegerVariableElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IntegerVariable");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cIntegerVariableAction_0 = (Action)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameEStringParserRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final Keyword cColonKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Keyword cIntegerKeyword_3 = (Keyword)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final Keyword cColonEqualsSignKeyword_4_0 = (Keyword)cGroup_4.eContents().get(0);
		private final Assignment cValueAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cValueIntegerDataParserRuleCall_4_1_0 = (RuleCall)cValueAssignment_4_1.eContents().get(0);
		
		//IntegerVariable:
		//	{IntegerVariable} name=EString ":" "integer" (":=" value=IntegerData)?;
		@Override public ParserRule getRule() { return rule; }

		//{IntegerVariable} name=EString ":" "integer" (":=" value=IntegerData)?
		public Group getGroup() { return cGroup; }

		//{IntegerVariable}
		public Action getIntegerVariableAction_0() { return cIntegerVariableAction_0; }

		//name=EString
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//EString
		public RuleCall getNameEStringParserRuleCall_1_0() { return cNameEStringParserRuleCall_1_0; }

		//":"
		public Keyword getColonKeyword_2() { return cColonKeyword_2; }

		//"integer"
		public Keyword getIntegerKeyword_3() { return cIntegerKeyword_3; }

		//(":=" value=IntegerData)?
		public Group getGroup_4() { return cGroup_4; }

		//":="
		public Keyword getColonEqualsSignKeyword_4_0() { return cColonEqualsSignKeyword_4_0; }

		//value=IntegerData
		public Assignment getValueAssignment_4_1() { return cValueAssignment_4_1; }

		//IntegerData
		public RuleCall getValueIntegerDataParserRuleCall_4_1_0() { return cValueIntegerDataParserRuleCall_4_1_0; }
	}
	
	
	public class OperatorElements extends AbstractEnumRuleElementFinder {
		private final EnumRule rule = (EnumRule) GrammarUtil.findRuleForName(getGrammar(), "Operator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final EnumLiteralDeclaration cAddEnumLiteralDeclaration_0 = (EnumLiteralDeclaration)cAlternatives.eContents().get(0);
		private final Keyword cAddAddKeyword_0_0 = (Keyword)cAddEnumLiteralDeclaration_0.eContents().get(0);
		private final EnumLiteralDeclaration cSubEnumLiteralDeclaration_1 = (EnumLiteralDeclaration)cAlternatives.eContents().get(1);
		private final Keyword cSubSubKeyword_1_0 = (Keyword)cSubEnumLiteralDeclaration_1.eContents().get(0);
		private final EnumLiteralDeclaration cEqEnumLiteralDeclaration_2 = (EnumLiteralDeclaration)cAlternatives.eContents().get(2);
		private final Keyword cEqEqKeyword_2_0 = (Keyword)cEqEnumLiteralDeclaration_2.eContents().get(0);
		private final EnumLiteralDeclaration cMulEnumLiteralDeclaration_3 = (EnumLiteralDeclaration)cAlternatives.eContents().get(3);
		private final Keyword cMulMulKeyword_3_0 = (Keyword)cMulEnumLiteralDeclaration_3.eContents().get(0);
		private final EnumLiteralDeclaration cGtEnumLiteralDeclaration_4 = (EnumLiteralDeclaration)cAlternatives.eContents().get(4);
		private final Keyword cGtGtKeyword_4_0 = (Keyword)cGtEnumLiteralDeclaration_4.eContents().get(0);
		private final EnumLiteralDeclaration cLtEnumLiteralDeclaration_5 = (EnumLiteralDeclaration)cAlternatives.eContents().get(5);
		private final Keyword cLtLtKeyword_5_0 = (Keyword)cLtEnumLiteralDeclaration_5.eContents().get(0);
		private final EnumLiteralDeclaration cLteEnumLiteralDeclaration_6 = (EnumLiteralDeclaration)cAlternatives.eContents().get(6);
		private final Keyword cLteLteKeyword_6_0 = (Keyword)cLteEnumLiteralDeclaration_6.eContents().get(0);
		private final EnumLiteralDeclaration cGteEnumLiteralDeclaration_7 = (EnumLiteralDeclaration)cAlternatives.eContents().get(7);
		private final Keyword cGteGteKeyword_7_0 = (Keyword)cGteEnumLiteralDeclaration_7.eContents().get(0);
		private final EnumLiteralDeclaration cDivEnumLiteralDeclaration_8 = (EnumLiteralDeclaration)cAlternatives.eContents().get(8);
		private final Keyword cDivDivKeyword_8_0 = (Keyword)cDivEnumLiteralDeclaration_8.eContents().get(0);
		private final EnumLiteralDeclaration cAndEnumLiteralDeclaration_9 = (EnumLiteralDeclaration)cAlternatives.eContents().get(9);
		private final Keyword cAndAndKeyword_9_0 = (Keyword)cAndEnumLiteralDeclaration_9.eContents().get(0);
		private final EnumLiteralDeclaration cNeqEnumLiteralDeclaration_10 = (EnumLiteralDeclaration)cAlternatives.eContents().get(10);
		private final Keyword cNeqNeqKeyword_10_0 = (Keyword)cNeqEnumLiteralDeclaration_10.eContents().get(0);
		private final EnumLiteralDeclaration cOrEnumLiteralDeclaration_11 = (EnumLiteralDeclaration)cAlternatives.eContents().get(11);
		private final Keyword cOrOrKeyword_11_0 = (Keyword)cOrEnumLiteralDeclaration_11.eContents().get(0);
		private final EnumLiteralDeclaration cNotEnumLiteralDeclaration_12 = (EnumLiteralDeclaration)cAlternatives.eContents().get(12);
		private final Keyword cNotNotKeyword_12_0 = (Keyword)cNotEnumLiteralDeclaration_12.eContents().get(0);
		
		//enum Operator:
		//	add | sub | eq | mul | gt | lt | lte | gte | div | and | neq | or | not;
		public EnumRule getRule() { return rule; }

		//add | sub | eq | mul | gt | lt | lte | gte | div | and | neq | or | not
		public Alternatives getAlternatives() { return cAlternatives; }

		//add
		public EnumLiteralDeclaration getAddEnumLiteralDeclaration_0() { return cAddEnumLiteralDeclaration_0; }

		//"add"
		public Keyword getAddAddKeyword_0_0() { return cAddAddKeyword_0_0; }

		//sub
		public EnumLiteralDeclaration getSubEnumLiteralDeclaration_1() { return cSubEnumLiteralDeclaration_1; }

		//"sub"
		public Keyword getSubSubKeyword_1_0() { return cSubSubKeyword_1_0; }

		//eq
		public EnumLiteralDeclaration getEqEnumLiteralDeclaration_2() { return cEqEnumLiteralDeclaration_2; }

		//"eq"
		public Keyword getEqEqKeyword_2_0() { return cEqEqKeyword_2_0; }

		//mul
		public EnumLiteralDeclaration getMulEnumLiteralDeclaration_3() { return cMulEnumLiteralDeclaration_3; }

		//"mul"
		public Keyword getMulMulKeyword_3_0() { return cMulMulKeyword_3_0; }

		//gt
		public EnumLiteralDeclaration getGtEnumLiteralDeclaration_4() { return cGtEnumLiteralDeclaration_4; }

		//"gt"
		public Keyword getGtGtKeyword_4_0() { return cGtGtKeyword_4_0; }

		//lt
		public EnumLiteralDeclaration getLtEnumLiteralDeclaration_5() { return cLtEnumLiteralDeclaration_5; }

		//"lt"
		public Keyword getLtLtKeyword_5_0() { return cLtLtKeyword_5_0; }

		//lte
		public EnumLiteralDeclaration getLteEnumLiteralDeclaration_6() { return cLteEnumLiteralDeclaration_6; }

		//"lte"
		public Keyword getLteLteKeyword_6_0() { return cLteLteKeyword_6_0; }

		//gte
		public EnumLiteralDeclaration getGteEnumLiteralDeclaration_7() { return cGteEnumLiteralDeclaration_7; }

		//"gte"
		public Keyword getGteGteKeyword_7_0() { return cGteGteKeyword_7_0; }

		//div
		public EnumLiteralDeclaration getDivEnumLiteralDeclaration_8() { return cDivEnumLiteralDeclaration_8; }

		//"div"
		public Keyword getDivDivKeyword_8_0() { return cDivDivKeyword_8_0; }

		//and
		public EnumLiteralDeclaration getAndEnumLiteralDeclaration_9() { return cAndEnumLiteralDeclaration_9; }

		//"and"
		public Keyword getAndAndKeyword_9_0() { return cAndAndKeyword_9_0; }

		//neq
		public EnumLiteralDeclaration getNeqEnumLiteralDeclaration_10() { return cNeqEnumLiteralDeclaration_10; }

		//"neq"
		public Keyword getNeqNeqKeyword_10_0() { return cNeqNeqKeyword_10_0; }

		//or
		public EnumLiteralDeclaration getOrEnumLiteralDeclaration_11() { return cOrEnumLiteralDeclaration_11; }

		//"or"
		public Keyword getOrOrKeyword_11_0() { return cOrOrKeyword_11_0; }

		//not
		public EnumLiteralDeclaration getNotEnumLiteralDeclaration_12() { return cNotEnumLiteralDeclaration_12; }

		//"not"
		public Keyword getNotNotKeyword_12_0() { return cNotNotKeyword_12_0; }
	}
	
	private final StateMachineElements pStateMachine;
	private final StateElements pState;
	private final VariableElements pVariable;
	private final ExpressionElementElements pExpressionElement;
	private final DataElements pData;
	private final EStringElements pEString;
	private final EBooleanElements pEBoolean;
	private final OperationElements pOperation;
	private final State_ImplElements pState_Impl;
	private final InitialStateElements pInitialState;
	private final TransitionElements pTransition;
	private final EventElements pEvent;
	private final AssignmentElements pAssignment;
	private final ExpressionElements pExpression;
	private final BooleanDataElements pBooleanData;
	private final IntegerDataElements pIntegerData;
	private final VariableReferenceElements pVariableReference;
	private final OperatorElements unknownRuleOperator;
	private final EIntElements pEInt;
	private final CompositeState_ImplElements pCompositeState_Impl;
	private final BooleanVariableElements pBooleanVariable;
	private final IntegerVariableElements pIntegerVariable;
	
	private final Grammar grammar;

	private final TerminalsGrammarAccess gaTerminals;

	@Inject
	public SMGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammar = internalFindGrammar(grammarProvider);
		this.gaTerminals = gaTerminals;
		this.pStateMachine = new StateMachineElements();
		this.pState = new StateElements();
		this.pVariable = new VariableElements();
		this.pExpressionElement = new ExpressionElementElements();
		this.pData = new DataElements();
		this.pEString = new EStringElements();
		this.pEBoolean = new EBooleanElements();
		this.pOperation = new OperationElements();
		this.pState_Impl = new State_ImplElements();
		this.pInitialState = new InitialStateElements();
		this.pTransition = new TransitionElements();
		this.pEvent = new EventElements();
		this.pAssignment = new AssignmentElements();
		this.pExpression = new ExpressionElements();
		this.pBooleanData = new BooleanDataElements();
		this.pIntegerData = new IntegerDataElements();
		this.pVariableReference = new VariableReferenceElements();
		this.unknownRuleOperator = new OperatorElements();
		this.pEInt = new EIntElements();
		this.pCompositeState_Impl = new CompositeState_ImplElements();
		this.pBooleanVariable = new BooleanVariableElements();
		this.pIntegerVariable = new IntegerVariableElements();
	}
	
	protected Grammar internalFindGrammar(GrammarProvider grammarProvider) {
		Grammar grammar = grammarProvider.getGrammar(this);
		while (grammar != null) {
			if ("org.xtext.StateMachine.sm.SM".equals(grammar.getName())) {
				return grammar;
			}
			List<Grammar> grammars = grammar.getUsedGrammars();
			if (!grammars.isEmpty()) {
				grammar = grammars.iterator().next();
			} else {
				return null;
			}
		}
		return grammar;
	}
	
	@Override
	public Grammar getGrammar() {
		return grammar;
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//StateMachine:
	//	isActive?="isActive" "StateMachine" name=EString "{" variables+=Variable* "events" "{" events+=Event (","
	//	events+=Event)* "}" / *('operation' operation=Operation)?
	//		'states' '{' states+=State ( "," states+=State)* '}' 
	//		'initialState' initialState=InitialState
	//		'transitions' '{' transitions+=Transition ( "," transitions+=Transition)* '}' 
	//		'events' '{' events+=Event ( "," events+=Event)* '}' 
	//		('variables' '{' variables+=Variable ( "," variables+=Variable)* '}' )?* / "}";
	public StateMachineElements getStateMachineAccess() {
		return pStateMachine;
	}
	
	public ParserRule getStateMachineRule() {
		return getStateMachineAccess().getRule();
	}

	//State:
	//	State_Impl | StateMachine | CompositeState_Impl;
	public StateElements getStateAccess() {
		return pState;
	}
	
	public ParserRule getStateRule() {
		return getStateAccess().getRule();
	}

	//Variable:
	//	"var" (BooleanVariable | IntegerVariable);
	public VariableElements getVariableAccess() {
		return pVariable;
	}
	
	public ParserRule getVariableRule() {
		return getVariableAccess().getRule();
	}

	//ExpressionElement:
	//	Expression | BooleanData | IntegerData | VariableReference;
	public ExpressionElementElements getExpressionElementAccess() {
		return pExpressionElement;
	}
	
	public ParserRule getExpressionElementRule() {
		return getExpressionElementAccess().getRule();
	}

	//Data:
	//	BooleanData | IntegerData;
	public DataElements getDataAccess() {
		return pData;
	}
	
	public ParserRule getDataRule() {
		return getDataAccess().getRule();
	}

	//EString returns ecore::EString:
	//	STRING | ID;
	public EStringElements getEStringAccess() {
		return pEString;
	}
	
	public ParserRule getEStringRule() {
		return getEStringAccess().getRule();
	}

	//EBoolean returns ecore::EBoolean:
	//	"true" | "false";
	public EBooleanElements getEBooleanAccess() {
		return pEBoolean;
	}
	
	public ParserRule getEBooleanRule() {
		return getEBooleanAccess().getRule();
	}

	//Operation:
	//	{Operation} "Operation" "{" ("contents" "{" contents+=Assignment ("," contents+=Assignment)* "}")? "}";
	public OperationElements getOperationAccess() {
		return pOperation;
	}
	
	public ParserRule getOperationRule() {
		return getOperationAccess().getRule();
	}

	//State_Impl returns State:
	//	isActive?="isActive" "State" name=EString "{" ("operation" operation=Operation)? "}";
	public State_ImplElements getState_ImplAccess() {
		return pState_Impl;
	}
	
	public ParserRule getState_ImplRule() {
		return getState_ImplAccess().getRule();
	}

	//InitialState:
	//	"InitialState" "{" "referencedState" referencedState=[State|EString] "}";
	public InitialStateElements getInitialStateAccess() {
		return pInitialState;
	}
	
	public ParserRule getInitialStateRule() {
		return getInitialStateAccess().getRule();
	}

	//Transition:
	//	"Transition" "{" "source" source=[State|EString] "target" target=[State|EString] "event" event=[Event|EString]
	//	("guard" guard=Expression)? "}";
	public TransitionElements getTransitionAccess() {
		return pTransition;
	}
	
	public ParserRule getTransitionRule() {
		return getTransitionAccess().getRule();
	}

	//Event:
	//	{Event} name=STRING;
	public EventElements getEventAccess() {
		return pEvent;
	}
	
	public ParserRule getEventRule() {
		return getEventAccess().getRule();
	}

	//Assignment:
	//	"Assignment" "{" ("_name" _name=EString)? "variable" variable=[Variable|EString] "expression"
	//	expression=ExpressionElement "}";
	public AssignmentElements getAssignmentAccess() {
		return pAssignment;
	}
	
	public ParserRule getAssignmentRule() {
		return getAssignmentAccess().getRule();
	}

	//Expression:
	//	"Expression" "{" "operator" operator=Operator ("_name" _name=EString)? "left" left=ExpressionElement "right"
	//	right=ExpressionElement "}";
	public ExpressionElements getExpressionAccess() {
		return pExpression;
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//BooleanData:
	//	value=EBoolean;
	public BooleanDataElements getBooleanDataAccess() {
		return pBooleanData;
	}
	
	public ParserRule getBooleanDataRule() {
		return getBooleanDataAccess().getRule();
	}

	//IntegerData:
	//	value=EInt;
	public IntegerDataElements getIntegerDataAccess() {
		return pIntegerData;
	}
	
	public ParserRule getIntegerDataRule() {
		return getIntegerDataAccess().getRule();
	}

	//VariableReference:
	//	"VariableReference" "{" ("_name" _name=EString)? "variable" variable=[Variable|EString] "}";
	public VariableReferenceElements getVariableReferenceAccess() {
		return pVariableReference;
	}
	
	public ParserRule getVariableReferenceRule() {
		return getVariableReferenceAccess().getRule();
	}

	//enum Operator:
	//	add | sub | eq | mul | gt | lt | lte | gte | div | and | neq | or | not;
	public OperatorElements getOperatorAccess() {
		return unknownRuleOperator;
	}
	
	public EnumRule getOperatorRule() {
		return getOperatorAccess().getRule();
	}

	//EInt returns ecore::EInt:
	//	"-"? INT;
	public EIntElements getEIntAccess() {
		return pEInt;
	}
	
	public ParserRule getEIntRule() {
		return getEIntAccess().getRule();
	}

	//CompositeState_Impl returns CompositeState:
	//	isActive?="isActive" "CompositeState" name=EString "{" ("operation" operation=Operation)? "states" "{" states+=State
	//	("," states+=State)* "}" "initialState" initialState=InitialState "}";
	public CompositeState_ImplElements getCompositeState_ImplAccess() {
		return pCompositeState_Impl;
	}
	
	public ParserRule getCompositeState_ImplRule() {
		return getCompositeState_ImplAccess().getRule();
	}

	//BooleanVariable:
	//	{BooleanVariable} name=EString ":" "boolean" (":=" value=BooleanData)?;
	public BooleanVariableElements getBooleanVariableAccess() {
		return pBooleanVariable;
	}
	
	public ParserRule getBooleanVariableRule() {
		return getBooleanVariableAccess().getRule();
	}

	//IntegerVariable:
	//	{IntegerVariable} name=EString ":" "integer" (":=" value=IntegerData)?;
	public IntegerVariableElements getIntegerVariableAccess() {
		return pIntegerVariable;
	}
	
	public ParserRule getIntegerVariableRule() {
		return getIntegerVariableAccess().getRule();
	}

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" . / * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\""))* "\"" | "\'" ("\\" .
	//	/ * 'b'|'t'|'n'|'f'|'r'|'u'|'"'|"'"|'\\' * / | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
