/**
 * generated by Xtext
 */
package org.xtext.StateMachine.sm.serializer;

import org.xtext.StateMachine.sm.serializer.AbstractSMSemanticSequencer;

@SuppressWarnings("all")
public class SMSemanticSequencer extends AbstractSMSemanticSequencer {
}
