/**
 * generated by Xtext
 */
package org.xtext.StateMachine.sm.serializer;

import org.xtext.StateMachine.sm.serializer.AbstractSMSyntacticSequencer;

@SuppressWarnings("all")
public class SMSyntacticSequencer extends AbstractSMSyntacticSequencer {
}
